### ISSUE TITLE
Make stonking great again!

### ISSUE THREAD

**Issue by Fluboxer** [CecerMCProjects/NoChangeTheGame#10]
Okay, that one will sound as either most natural thing to do or as some stupid request depending of if you know skyblock or not 

SkyBlock is probably most promising hypixel's gamemode to be played on modern version - but doing so has literally two disadvantages:

1. Less polished skyblock mods 
2. No stonking

With 1 it is a question of time - [skyblocker's](https://github.com/SkyblockerMod/Skyblocker) devs are going at incredible pace and sooner or later it will have all major features 

However, there is 2nd issue, which is lack of stonking. Basically whole skyblock have custom mining system - except for private island, hub and... dungeons. And there is a "stonk", golden pickaxe with eff 6. Players quickly found out that you can go brrr trough wall and click something behind it - like chest behind bars, essence behind walls, etc. This thing works on 1.20, it is ping reliant and there is no need to do anything about it

However, there is another thing, which is ghost blocks - aka thing skyblock players now call "stonking". There are multiple ways of making them, most popular of which are swap stonking (swap non-pickaxe to pickaxe and hit at same time) and ghost pickaxe (hit two hotbar buttons at same time. Your real pickaxe at new slot, ghost pickaxe where real was before) which let 1.8.9 players create ghost blocks and either click stuff trough it or literally go in the walls. No, this is not "sweat" thing, literally every player that is not noob uses that. Yes, you are expected to be able to do this at higher dungeon floors. Yes, this is widely known thing. At this point it is more of a feature as admins several times **unfixed** it after fixing it - they are sure aware about it and know how to stop it 
*Speaking of which, it is not first instance of admins undoing patch of some bug or exploit regarding dungeons. For example, in recent alpha there was patch to ender pearls working in trap room - no one asked about it and after day of angry threads it was reverted*

On 1.20 stonking does not work due to mojang patching some stuff. Some kids are using viaversion (severe ban risk), other kids are probably cooking hacks (literally breaking rules; it is also far worse as it won't stop working if admins patch it for 1.8.9)

Perhaps you can unfix it so 1.20 can also do this without using bannable stuff?

**Comment by Cecer** [comment]
Unfortunately I don't think it would be appropriate to remove this particular bug fix. I don't think there is a way to do this without it essentially being a cheat feature. Interacting through a solid wall sounds like a great way to trigger some cheat detections if you ask me.

As for it being intentional, I'm not entirely convinced. There have been several situations where players riot about a "change" when no change took place then thank the admins for reverting the "change" a few days later... even though nothing was ever changed in the first place.

I know for a fact that ghost blocks can be a major pain and efforts have been made to reduce them in the past. Unfortunately it's not really possible to fix properly for old versions. I would expect an intentional feature such as this, would be done in code. It wouldn't be that complicated and would provide a much better player experience.
